version: '3'
services:
  app:
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME} npm run migrate up &&
             npm run dev"
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - db
  
  db:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - dev-db-todo:/var/lib/postgres
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  dev-db-todo: